// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Data;

#nullable disable

namespace Portfolio.Data.Migrations
{
    [DbContext(typeof(PortfolioContext))]
    partial class PortfolioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Data.Entities.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FunBadge")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusBadge")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Abouts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "I design and build thoughtful digital products — from responsive interfaces to robust backend systems. Passionate about clean code, great UX, and technology that actually matters.",
                            FullName = "Nikoloz Lortkipanidze",
                            FunBadge = "Building cool things",
                            JobTitle = "Full-Stack Developer",
                            StatusBadge = "Open to work"
                        });
                });

            modelBuilder.Entity("Portfolio.Data.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<int>("EmailJSId")
                        .HasColumnType("int");

                    b.Property<string>("GithubLink")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LinkedinLink")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmailJSId")
                        .IsUnique();

                    b.ToTable("Contacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "nikusha191208@gmail.com",
                            EmailJSId = 1,
                            GithubLink = "https://github.com/lortkipa",
                            LinkedinLink = "https://www.linkedin.com/in/nikoloz-lortkipanidze-2b4263329/",
                            Location = "Tbilisi, Georgia",
                            PhoneNumber = "+995 575 78 03 23"
                        });
                });

            modelBuilder.Entity("Portfolio.Data.Entities.EmailJS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PublicKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailJS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("Portfolio.Data.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Portfolio.Data.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Theme")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("demoLink")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("githubLink")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Desc")
                        .IsUnique();

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("demoLink")
                        .IsUnique()
                        .HasFilter("[demoLink] IS NOT NULL");

                    b.HasIndex("githubLink")
                        .IsUnique()
                        .HasFilter("[githubLink] IS NOT NULL");

                    b.ToTable("Projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Responsive developer portfolio built to showcase projects, skills, and professional experience with modern UI animations and clean design.",
                            Icon = "🌐",
                            Theme = 1,
                            Title = "Personal Portfolio Website",
                            githubLink = "https://github.com/lortkipa/portfolio"
                        });
                });

            modelBuilder.Entity("Portfolio.Data.Entities.ProjectTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TagId");

                    b.ToTable("ProjectTags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectId = 1,
                            TagId = 2
                        },
                        new
                        {
                            Id = 2,
                            ProjectId = 1,
                            TagId = 3
                        },
                        new
                        {
                            Id = 3,
                            ProjectId = 1,
                            TagId = 4
                        },
                        new
                        {
                            Id = 4,
                            ProjectId = 1,
                            TagId = 8
                        },
                        new
                        {
                            Id = 5,
                            ProjectId = 1,
                            TagId = 9
                        },
                        new
                        {
                            Id = 6,
                            ProjectId = 1,
                            TagId = 10
                        },
                        new
                        {
                            Id = 7,
                            ProjectId = 1,
                            TagId = 12
                        },
                        new
                        {
                            Id = 8,
                            ProjectId = 1,
                            TagId = 13
                        },
                        new
                        {
                            Id = 9,
                            ProjectId = 1,
                            TagId = 14
                        },
                        new
                        {
                            Id = 10,
                            ProjectId = 1,
                            TagId = 17
                        },
                        new
                        {
                            Id = 11,
                            ProjectId = 1,
                            TagId = 20
                        },
                        new
                        {
                            Id = 12,
                            ProjectId = 1,
                            TagId = 21
                        });
                });

            modelBuilder.Entity("Portfolio.Data.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "💻",
                            Title = "Languages"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "🎨",
                            Title = "Frontend"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "⚙️",
                            Title = "Backend"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "🗄️",
                            Title = "Databases & Cloud"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "🔧",
                            Title = "Tools & DevOps"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "🤝",
                            Title = "Soft Skills"
                        });
                });

            modelBuilder.Entity("Portfolio.Data.Entities.SkillTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("TagId");

                    b.ToTable("SkillTags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SkillId = 1,
                            TagId = 1
                        },
                        new
                        {
                            Id = 2,
                            SkillId = 1,
                            TagId = 2
                        },
                        new
                        {
                            Id = 3,
                            SkillId = 1,
                            TagId = 3
                        },
                        new
                        {
                            Id = 4,
                            SkillId = 1,
                            TagId = 4
                        },
                        new
                        {
                            Id = 5,
                            SkillId = 1,
                            TagId = 5
                        },
                        new
                        {
                            Id = 6,
                            SkillId = 1,
                            TagId = 6
                        },
                        new
                        {
                            Id = 7,
                            SkillId = 1,
                            TagId = 7
                        },
                        new
                        {
                            Id = 8,
                            SkillId = 2,
                            TagId = 8
                        },
                        new
                        {
                            Id = 9,
                            SkillId = 2,
                            TagId = 9
                        },
                        new
                        {
                            Id = 10,
                            SkillId = 2,
                            TagId = 10
                        },
                        new
                        {
                            Id = 11,
                            SkillId = 2,
                            TagId = 11
                        },
                        new
                        {
                            Id = 12,
                            SkillId = 3,
                            TagId = 12
                        },
                        new
                        {
                            Id = 13,
                            SkillId = 3,
                            TagId = 13
                        },
                        new
                        {
                            Id = 14,
                            SkillId = 3,
                            TagId = 14
                        },
                        new
                        {
                            Id = 15,
                            SkillId = 4,
                            TagId = 15
                        },
                        new
                        {
                            Id = 16,
                            SkillId = 4,
                            TagId = 16
                        },
                        new
                        {
                            Id = 17,
                            SkillId = 4,
                            TagId = 17
                        },
                        new
                        {
                            Id = 18,
                            SkillId = 5,
                            TagId = 18
                        },
                        new
                        {
                            Id = 19,
                            SkillId = 5,
                            TagId = 19
                        },
                        new
                        {
                            Id = 20,
                            SkillId = 5,
                            TagId = 20
                        },
                        new
                        {
                            Id = 21,
                            SkillId = 5,
                            TagId = 21
                        },
                        new
                        {
                            Id = 22,
                            SkillId = 5,
                            TagId = 22
                        },
                        new
                        {
                            Id = 23,
                            SkillId = 5,
                            TagId = 23
                        },
                        new
                        {
                            Id = 24,
                            SkillId = 6,
                            TagId = 24
                        },
                        new
                        {
                            Id = 25,
                            SkillId = 6,
                            TagId = 25
                        },
                        new
                        {
                            Id = 26,
                            SkillId = 6,
                            TagId = 26
                        });
                });

            modelBuilder.Entity("Portfolio.Data.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 2,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 5,
                            Name = "C"
                        },
                        new
                        {
                            Id = 6,
                            Name = "C++"
                        },
                        new
                        {
                            Id = 7,
                            Name = "x86-64 Assembly"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 9,
                            Name = "HTML"
                        },
                        new
                        {
                            Id = 10,
                            Name = "CSS / SCSS"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Figma"
                        },
                        new
                        {
                            Id = 12,
                            Name = ".NET"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Entity Framework Core"
                        },
                        new
                        {
                            Id = 14,
                            Name = "REST APIs"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Firebase"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Mock API"
                        },
                        new
                        {
                            Id = 17,
                            Name = "MySQL"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Git"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Linux"
                        },
                        new
                        {
                            Id = 20,
                            Name = "VS Code"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Visual Studio"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Neovim"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Makefile"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Team Leadership"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Code Review"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Mentoring"
                        });
                });

            modelBuilder.Entity("Portfolio.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AboutId")
                        .HasColumnType("int");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AboutId")
                        .IsUnique();

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutId = 1,
                            ContactId = 1,
                            PasswordHash = "poZOszmw4fbgDXUpOohAq/BposD+gublOvasCZeTwdU="
                        });
                });

            modelBuilder.Entity("Portfolio.Data.Entities.Contact", b =>
                {
                    b.HasOne("Portfolio.Data.Entities.EmailJS", "EmailJS")
                        .WithOne("Contact")
                        .HasForeignKey("Portfolio.Data.Entities.Contact", "EmailJSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailJS");
                });

            modelBuilder.Entity("Portfolio.Data.Entities.ProjectTag", b =>
                {
                    b.HasOne("Portfolio.Data.Entities.Project", "Project")
                        .WithMany("ProjectTags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Data.Entities.Tag", "Tag")
                        .WithMany("ProjectTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Portfolio.Data.Entities.SkillTag", b =>
                {
                    b.HasOne("Portfolio.Data.Entities.Skill", "Skill")
                        .WithMany("SkillTags")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Data.Entities.Tag", "Tag")
                        .WithMany("SkillTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Portfolio.Data.Entities.User", b =>
                {
                    b.HasOne("Portfolio.Data.Entities.About", "About")
                        .WithOne("User")
                        .HasForeignKey("Portfolio.Data.Entities.User", "AboutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Data.Entities.Contact", "Contact")
                        .WithOne("User")
                        .HasForeignKey("Portfolio.Data.Entities.User", "ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("About");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Portfolio.Data.Entities.About", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Portfolio.Data.Entities.Contact", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Portfolio.Data.Entities.EmailJS", b =>
                {
                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Portfolio.Data.Entities.Project", b =>
                {
                    b.Navigation("ProjectTags");
                });

            modelBuilder.Entity("Portfolio.Data.Entities.Skill", b =>
                {
                    b.Navigation("SkillTags");
                });

            modelBuilder.Entity("Portfolio.Data.Entities.Tag", b =>
                {
                    b.Navigation("ProjectTags");

                    b.Navigation("SkillTags");
                });
#pragma warning restore 612, 618
        }
    }
}
